version: '3'
services:
  registration-service-db:
    container_name: registration-service-db
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-very_secret}
      POSTGRES_DB: ${DATABASE_NAME:-db_first}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
       - b-bot-net
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - registration-service-db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin@admin}
      PGADMIN_LISTEN_PORT: 43251
    networks:
      - b-bot-net
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "6071:43251"

networks:
   b-bot-net:
     driver: bridge

volumes:
  postgres-data:
    driver: local
  pgadmin:
    driver: local
